---
# tasks file for 01_master
  - name: Running install.sh on Master
    shell: INSTALL_K3S_SKIP_DOWNLOAD=true /home/{{ ansible_user }}/install.sh
    become: true
    when: "'master' is in ansible_hostname"

  - name: adding configuration to the service
    lineinfile:
      path: "/etc/systemd/system/k3s.service"
      line: "--write-kubeconfig-mode 775"
    become: true
    when: "'master' is in ansible_hostname"

  - name: Adding env variable
    lineinfile:
      path: "/etc/systemd/system/k3s.service.env"
      line: "K3S_KUBECONFIG_MODE='644'"
    become: true
    when: "'master' is in ansible_hostname"

  - name: "Restarting daemon and k3s"
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl restart k3s.service
    become: true
    when: "'master' is in ansible_hostname"

  - name: Extract token from master
    shell: "sudo cat /var/lib/rancher/k3s/server/token"
    register: master_token
    become: true
    run_once: true
    when: "'master' is in ansible_hostname"
  
  - name: Set master token as fact for all hosts
    set_fact:
      master_token_shared: "{{ master_token.stdout }}"
    run_once: true
    when: "'master' is in ansible_hostname"