version: "3.0"

services:
  ansible-host:
    hostname: ansible-host
    build:
      context: .
      dockerfile: Dockerfile.ansible
    command: ["sleep", "500000"]
    networks:
      - vaiolabs.io
    volumes:
      - ../:/home/ansible/ansible_course
  k3s_master:
    hostname: k3s_master
    build:
      context: .
      dockerfile: Dockerfile.deb
    environment:
      SSH_USERNAME: docker
      SSH_USERPASS: docker
    command: ["/usr/sbin/sshd", "-D"]
    networks:
      - vaiolabs.io
    volumes:
      - ../:/home/ansible/ansible_course
  k3s_slave:
    hostname: k3s_slave
    build:
      context: .
      dockerfile: Dockerfile.deb
    environment:
      SSH_USERNAME: docker
      SSH_USERPASS: docker
    command: ["/usr/sbin/sshd", "-D"]
    networks:
      - vaiolabs.io
    volumes:
      - ../:/home/ansible/ansible_course


networks:
  vaiolabs.io:
    name: vaiolabs.io
