---
# tasks file for master
  - name: Copy k3s Binary to /usr/local/bin
    copy:
      src: k3s
      dest: /usr/local/bin/k3s
      mode: "0711"
    become: true


  - name: Create folder for the k3s images, if doesn't already exist
    file:
      path: "/var/lib/rancher/k3s/agent/images/"
      state: directory
      mode: '0755'
    ignore_errors: true
    become: true
  
  - name: Copy k3s images to /var/lib/rancher/k3s/agent
    copy:
      src: master/files/k3s-airgap-images-amd64.tar.zst
      dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-amd64.tar.zst
      mode: "0711"
    become: true

  - name: Copy install script to the target's temp folder, to be run to install k3s
    copy:
      src: master/files/install.sh
      dest: /home/{{ ansible_user }}/install.sh
      mode: "0711"
    become: true

  - name: Running install.sh on Master
    shell: INSTALL_K3S_SKIP_DOWNLOAD=true /home/{{ ansible_user }}/install.sh
    become: true
    when: "'master' is in ansible_hostname"

  - name: adding configuration to the service
    lineinfile:
      path: "/etc/systemd/system/k3s.service"
      line: "--write-kubeconfig-mode 775"
    become: true
    when: "'master' is in ansible_hostname"

  - name: Adding env variable
    lineinfile:
      path: "/etc/systemd/system/k3s.service.env"
      line: "K3S_KUBECONFIG_MODE='644'"
    become: true
    when: "'master' is in ansible_hostname"

  - name: Restarting daemon and k3s
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl restart k3s.service
    become: true
    when: "'master' is in ansible_hostname"

  - name: Extract token from master
    shell: "sudo cat /var/lib/rancher/k3s/server/token"
    register: master_token
    become: true
    run_once: true
    when: "'master' is in ansible_hostname"
  
  - name: Set master token as fact for all hosts
    set_fact:
      master_token_shared: "{{ master_token.stdout }}"
    run_once: true
    when: "'master' is in ansible_hostname"


  - name: Running install.sh on Slave
    shell: INSTALL_K3S_SKIP_DOWNLOAD=true K3S_URL=https://192.168.1.2:6443 K3S_TOKEN="{{ master_token_shared }}" /home/"{{ ansible_user }}"/install.sh
    become: true
    when: "'slave' is in ansible_hostname"

